# Generated by Django 4.1 on 2023-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="dishModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("pic", models.ImageField(upload_to="foodImages/")),
                ("type", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
