# Generated by Django 4.1 on 2023-05-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_menumodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="userPropertiesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isDelivery", models.IntegerField()),
                ("isAdmin", models.IntegerField()),
                (
                    "isOwner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.hotelmodel",
                    ),
                ),
            ],
        ),
    ]
