# Generated by Django 4.1 on 2023-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_cartmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="promocodesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("value", models.IntegerField()),
                ("maxUse", models.IntegerField()),
                ("usedtillnow", models.IntegerField()),
            ],
        ),
    ]
