# Generated by Django 4.2.1 on 2023-05-21 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0007_alter_hotelmodel_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpropertiesmodel",
            name="userprop",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpropertiesmodel",
            name="isOwner",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.hotelmodel",
            ),
        ),
    ]
